my_social_project/app_login/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
# from django.contrib.staticfiles.urls import static,staticfiles_urlpatterns
from app_login import views


app_name='app_login'
urlpatterns = [
    path('signup/',views.sign_up,name='signup' ),
    path('login/',views.login_page,name='login' ),
    path('profile/',views.profile,name='profile' ),
    path('logout/',views.logout_user,name='logout' ),
    path('edit-profile/',views.edit_profile,name='edit_profile' ),
    path('user/<str:username>/',views.user,name='user'),
    path('follow/<str:username>/',views.follow,name='follow'),
    path('unfollow/<str:username>/',views.unfollow,name='unfollow'),
    
]

my_social_project/app_post/urls.py
from app_post import views
from django.urls import path


app_name='app_post'


urlpatterns=[
    path('',views.home,name='home')
]

my_social_project/my_social_project/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.contrib.staticfiles.urls import static,staticfiles_urlpatterns
from app_post import views
urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/',include('app_login.urls')),
    path('post/',include('app_post.urls')),
    path('',views.home,name='home'),
]

urlpatterns+=static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)
urlpatterns+=static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)

my_social_project/app_login/models.py
from django.db import models
from django.contrib.auth.models import User
from django.contrib.auth.models import AbstractUser

# Create your models here.
class UserProfile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE,related_name='user_profile')
    profile_pic=models.ImageField(upload_to='profile_pics',blank=True)
    description=models.CharField(max_length=264,blank=True)
    dob=models.DateField(blank=True,null=True)
    full_name=models.CharField(max_length=264,blank=True)
    website=models.URLField(blank=True)
    facebook=models.URLField(blank=True)
    
    def __str__(self):
        return self.user.username


class Follow(models.Model):
    follower=models.ForeignKey(User,related_name='follower',on_delete=models.CASCADE)
    following=models.ForeignKey(User,related_name='following',on_delete=models.CASCADE)
    created_date=models.DateTimeField(auto_now_add=True)

my_social_project/app_login/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth.models import User
from app_login.models import UserProfile


class CreateNewUser(UserCreationForm):
    email=forms.EmailField(required=True,label='',widget=forms.TextInput(attrs={'placeholder':"Email"}))
    username=forms.CharField(required=True,label='',widget=forms.TextInput(attrs={'placeholder':"Username"}))
    password1=forms.CharField(required=True,label='',widget=forms.PasswordInput(attrs={'placeholder':'Password'}))
    password2=forms.CharField(required=True,label='',widget=forms.PasswordInput(attrs={'placeholder':'Password confirmation'}))
    class Meta:
        model = User
        fields=['username','email','password1','password2',]
        
        
class LoginUserForm(AuthenticationForm):
    username=forms.CharField(required=True,label='',widget=forms.TextInput(attrs={'placeholder':'username'}))
    password=forms.CharField(required=True,label='',widget=forms.PasswordInput(attrs={'placeholder':'Password'}))
    class Meta:
        model = User
        fields=['username','password']
        
class EditProfileForm(forms.ModelForm):
    dob=forms.DateField(widget=forms.TextInput(attrs={'type':'date',}))
    class Meta:
        model=UserProfile 
        fields='__all__'

my_social_project/app_login/views.py
from django.shortcuts import render,HttpResponseRedirect
from django.contrib.auth import authenticate,login,logout
from app_login.forms import CreateNewUser,LoginUserForm,EditProfileForm
from django.urls import reverse_lazy,reverse
from app_login.models import UserProfile,Follow
from django.contrib.auth.decorators import login_required
from app_post.forms import PostForm
from django.contrib.auth.models import User
# Create your views here.

def sign_up(request):
    form = CreateNewUser()
    dict={
        'form':form,
        'title':'SignUp',
    }
    if request.method=="POST":
        form = CreateNewUser(data=request.POST)
        if form.is_valid():
            user=form.save()
            dict.update({'form':form,'registered':True})
            user_profile=UserProfile(user=user)
            user_profile.save()
            return HttpResponseRedirect(reverse('app_login:login'))
        else:
            dict.update({'form':form,'registered':False})
    return render(request,'app_login/signup.html',context=dict)

def login_page(request):
    form=LoginUserForm()
    dict={
        'form':form,
        'title':'Login',
    }
    if request.method=="POST":
        form=LoginUserForm(data=request.POST)
        if form.is_valid():
            username=form.cleaned_data.get('username')
            password=form.cleaned_data.get('password')
            user=authenticate(username=username,password=password)
            if user is not None:
                login(request,user)
                return HttpResponseRedirect(reverse('app_post:home'))
    else:
        return render(request,"app_login/login.html",context=dict)
    
@login_required           
def edit_profile(request):
    current_user=UserProfile.objects.get(user=request.user)
    form=EditProfileForm(instance=current_user)
    if request.method=="POST":
        form=EditProfileForm(request.POST,request.FILES,instance=current_user)
        if form.is_valid():
            form.save(commit=True)
            form=EditProfileForm(instance=current_user)
            return HttpResponseRedirect (reverse('app_login:profile'))
    
    return render(request,'app_login/profile.html',context={'title':'Edit Profile',
        "form":form,})


@login_required
def logout_user(request):
        logout(request)
        return HttpResponseRedirect(reverse('app_login:login'))
    
@login_required
def profile(request):
    form=PostForm()
    if request.method =="POST":
        form=PostForm(request.POST,request.FILES)
        if form.is_valid():
            post=form.save(commit=False)
            post.author=request.user
            post.save()
            return HttpResponseRedirect(reverse('home'))
    
    return render(request,'app_login/user.html',context={'title':'User','form':form})

@login_required
def user(request,username):
    user_other=User.objects.get(username=username)
    already_followed=Follow.objects.filter(follower=request.user,following=user_other)
    if user_other==request.user:
        return HttpResponseRedirect(reverse('app_login:profile'))
    return render(request,'app_login/user_other.html',context={'user_other':user_other ,'already_followed': already_followed})
    

@login_required
def follow(request,username):
    following_user=User.objects.get(username=username)
    follower_user=request.user
    already_followed=Follow.objects.filter(follower=follower_user,following=following_user)
    if not already_followed:
        followed_user=Follow(follower=follower_user,following=following_user)
        followed_user.save()
    return HttpResponseRedirect (reverse('app_login:user',kwargs={'username':username}))

@login_required
def unfollow(request,username):
    following_user=User.objects.get(username=username)
    follower_user=request.user
    already_followed=Follow.objects.filter(follower=follower_user,following=following_user)
    already_followed.delete()
    return HttpResponseRedirect(reverse('app_login:user',kwargs={'username':username}))

my_social_project/templates/app_login/login.html
{%extends 'base.html'%}
{%load crispy_forms_tags %}
{%block title_block%}
{{title}}
{%endblock%}
{%block css_block%}
<style>
.sign_up{
    width: 450px;
    border:1px solid #ccc;
    padding:20px;

}
.log_in{
    width: 450px;
    padding:10px;
    border: 1px solid #ccc;
    height: 50px;
}
</style>

{%endblock%}
{% block content %}
<center>
<div class="sign_up">
    <h3>Login</h3>
    <form action=""method='POST'>
        {{form|crispy}}
        {%csrf_token%}
        <input type="submit" name="submit" value="Login" style="width: 100%;" class="btn btn-primary">
    </form>
</div>
<br>
<div class="log_in">
    <p>Dont have an account?<a href="{%url 'app_login:signup'%}">Sign Up</a></p>


</div>
</center>

{%endblock%}

my_social_project/templates/app_login/profile.html
{%extends 'navbar.html'%}
{%load crispy_forms_tags %}
{%block title_block%}
{{title}}
{%endblock%}
{% block content %}
<form action=""method='POST' enctype="multipart/form-data">
    {{form|crispy}}
    {%csrf_token%}
    <input type="submit" name="submit" value="submit" class="btn btn-primary btn-sm">
</form>
{%endblock%}

my_social_project/templates/app_login/signup.html
{%extends 'base.html'%}
{%load crispy_forms_tags %}
{%block title_block%}
{{title}}
{%endblock%}
{%block css_block%}
<style>
.sign_up{
    width: 450px;
    border:1px solid #ccc;
    padding:20px;

}
.log_in{
    width: 450px;
    padding:10px;
    border: 1px solid #ccc;
    height: 50px;
}
</style>

{%endblock%}
{% block content %}
<center>
<div class="sign_up">
    <h3>Sign Up to see Photos From your friends.</h3>
    <form action=""method='POST'>
        {{form|crispy}}
        {%csrf_token%}
        <input type="submit" name="submit" value="Sign Up" style="width: 100%;" class="btn btn-primary">
    </form>
</div>
<br>
<div class="log_in">
    <p>Have an account?<a href="{%url 'app_login:login'%}">Login</a></p>
</div>
</center>

{%endblock%}

my_social_project/templates/app_login/user.html
{%extends 'navbar.html'%}
{%block title_block%}
{{user.user_profile.full_name}}(@{{user.username}})
{%endblock%}
{%block css_block%}
<style>
  .crop{
    width: 200px;
    height: 200px;
    overflow: hidden;
  }
  .crop img{
    width: 400px;
    height: 400px;
    margin: -75px 0 0 -100px;
  }
</style>
{%endblock%}

{% block content %}
<div class="row">
    <div class="col-sm-4">
        {%if user.user_profile.profile_pic%}
        <P><img src="/media/{{user.user_profile.profile_pic}}" alt="profile_pic" width="250px" height="250px" class="rounded-circle"></P>
        {%else%}
        <P><img src="/media/profile_pics/profile-pic.jpg" alt="profile_pic" height="250px" width="250px" class="rounded-circle"></P>
        {%endif%}
        <br>
    </div>
    <div class="col-sm-8">
        <h3>{{user.username}} &nbsp; <a href="{%url 'app_login:edit_profile'%}" class="btn btn-light">Edit profile</a></h3>
        <br>
        <h4>{{user.post.count}} posts &nbsp; &nbsp; {{user.following.count}} followors &nbsp; &nbsp;
            {{user.follower.count}} following </h4>
        <br>
        <h3>{{user.user_profile.full_name}}</h3>
        <h6>{{user.user_profile.description|linebreaks}}</h6>
    </div>

</div>
<hr>
<button type="button" class="btn btn-primary" data-toggle="modal" data-target="#myModal">
    New Post
  </button>
  <!-- The Modal -->
  <div class="modal" id="myModal">
    <div class="modal-dialog">
      <div class="modal-content">
      
        <!-- Modal Header -->
        <div class="modal-header">
          <h4 class="modal-title">Post a photo</h4>
          <button type="button" class="close" data-dismiss="modal">&times;</button>
        </div>
        
        <!-- Modal body -->
        <div class="modal-body">
          <form method="post" enctype="multipart/form-data">
            {%csrf_token%}
            {{form.as_p}}
            <button type="submit" >Post</button>
          </form>
        </div>
        
        <!-- Modal footer -->
        <div class="modal-footer">
          <button type="button" class="btn btn-danger" data-dismiss="modal">Close</button>
        </div>
        
      </div>
    </div>
  </div>
  <div class="row">
    {%for post in user.post.all%}
    <div class="crop">
      <img src="/media/{{post.image}}" title="{{post.caption}}">
      </div>
    {%endfor%}
  </div>
{%endblock%}

my_social_project/templates/app_login/user_other.html
{%extends 'navbar.html'%}
{%block title_block%}
{{user_other.user_profile.full_name}}(@{{user_other.username}})
{%endblock%}
{%block css_block%}
<style>
  .crop{
    width: 200px;
    height: 200px;
    overflow: hidden;
  }
  .crop img{
    width: 400px;
    height: 400px;
    margin: -75px 0 0 -100px;
  }
</style>
{%endblock%}
{%block content %}
<div class="row">
    <div class="col-sm-4">
        {%if user_other.user_profile.profile_pic%}
        <P><img src="/media/{{user_other.user_profile.profile_pic}}" alt="profile_pic" width="250px" height="250px" class="rounded-circle"></P>
        {%else%}
        <P><img src="/media/profile_pics/profile-pic.jpg" alt="profile_pic" height="250px" width="250px" class="rounded-circle"></P>
        {%endif%}
        <br>
    </div>
    <div class="col-sm-8">
        {%if not already_followed%}
        <h1>{{user_other.username}} &nbsp; <a class='btn btn-primary' href="{% url 'app_login:follow' username=user_other.username%}">Follow</a> </h1>
        <br>
        {%else%}
        <h1>{{user_other.username}} &nbsp; <a class='btn btn-primary' href="{% url 'app_login:unfollow' username=user_other.username%}">Unfollow</a> </h1>
        <br>
        {%endif%}
        <h4>{{user_other.post.count}} posts &nbsp; &nbsp; {{user_other.following.count}} followors &nbsp; &nbsp;
            {{user_other.follower.count}} following </h4>
        <br>
        <h3>{{user_other.user_profile.full_name}}</h3>
        <h6>{{user_other.user_profile.description|linebreaks}}</h6>
        
    </div>


</div>
<br>
<br>
<div class="row">
    {%for post in user_other.post.all%}
    <div class="crop">
      <img src="/media/{{post.image}}" title="{{post.caption}}">
      </div>
    {%endfor%}
  </div>


{%endblock%}