my_social_project/app_login/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
# from django.contrib.staticfiles.urls import static,staticfiles_urlpatterns
from app_login import views


app_name='app_login'
urlpatterns = [
    path('signup/',views.sign_up,name='signup' ),
    path('login/',views.login_page,name='login' ),
    path('profile/',views.profile,name='profile' ),
    path('logout/',views.logout_user,name='logout' ),
    path('edit-profile/',views.edit_profile,name='edit_profile' ),
    path('user/<str:username>/',views.user,name='user'),
    path('follow/<str:username>/',views.follow,name='follow'),
    path('unfollow/<str:username>/',views.unfollow,name='unfollow'),
    
]

my_social_project/app_post/urls.py
from app_post import views
from django.urls import path


app_name='app_post'


urlpatterns=[
    path('',views.home,name='home')
]

my_social_project/my_social_project/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.contrib.staticfiles.urls import static,staticfiles_urlpatterns
from app_post import views
urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/',include('app_login.urls')),
    path('post/',include('app_post.urls')),
    path('',views.home,name='home'),
]

urlpatterns+=static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)
urlpatterns+=static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)

my_social_project/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title_block %} Social  {% endblock %}</title>
        {%block css_block%}
        {%endblock%}
   <!-- Bootstrap CSS -->
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
</head>
<body>
    <!-- <nav class="navbar navbar-expand-sm bg-dark navbar-dark">
        <div class="container-fluid">
            <ul class="navbar-nav">
                <li class="nav-item">
                    <a class="nav-link" href="#">Home</a>
                </li>
            </ul>
        </div>
    </nav> -->
    
    <div class="container" style="padding-top: 20px;">
        {% block content %}

        {% endblock %}
    </div>

    <!-- Bootstrap JavaScript -->
  <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
  <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
</html>

my_social_project/templates/navbar.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title_block %} Social  {% endblock %}</title>
        {%block css_block%}
        {%endblock%}
   <!-- Bootstrap CSS -->
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
</head>
<body>
    <nav class="navbar navbar-expand-sm bg-dark navbar-dark">
        <div class="container-fluid">
            <ul class="navbar-nav">
                <li class="nav-item active">
                    <a class="nav-link" href="{%url 'app_post:home'%}">Home</a>
                </li>
                &nbsp; &nbsp; &nbsp; &nbsp;
                <form class="form-inline" method="GET">
                    <input class="form-control mr-sm-2" type="text" name="search" placeholder="Search">
                    <button class="btn btn-success" type="submit">Search</button>
                  </form>
                    {% if user.is_authenticated and user.is_staff %}
                    <li class="nav-item">
                        <a class="nav-link" href="/admin/" target="_blank">Admin Panel</a>
                    </li>
                    {% endif %}
                <li class="nav-item">
                    <a class="nav-link" href="{%url 'app_login:logout'%}">Logout</a>
                </li>
                <li class="nav-item">
                    {%if user.user_profile.profile_pic%}
                    <a class="nav-link" href="{%url 'app_login:profile'%}"><img src="/media/{{user.user_profile.profile_pic}}"  width='50px' width="50px" class="rounded-circle" alt=""></a>
                    {%else%}
                    <a class="nav-link" href="#"><img src="/media/profile_pics/profile-pic.jpg" width='50px' width="50px" class="rounded-circle" alt=""></a>
                    {%endif%}
                </li>
            </ul>
        </div>
    </nav>
    
    <div class="container" style="padding-top: 30px;">
        {% block content %}

        {% endblock %}
    </div>

    <!-- Bootstrap JavaScript -->
  <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
  <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
</html>