my_social_project/app_login/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
# from django.contrib.staticfiles.urls import static,staticfiles_urlpatterns
from app_login import views


app_name='app_login'
urlpatterns = [
    path('signup/',views.sign_up,name='signup' ),
    path('login/',views.login_page,name='login' ),
    path('profile/',views.profile,name='profile' ),
    path('logout/',views.logout_user,name='logout' ),
    path('edit-profile/',views.edit_profile,name='edit_profile' ),
    path('user/<str:username>/',views.user,name='user'),
    path('follow/<str:username>/',views.follow,name='follow'),
    path('unfollow/<str:username>/',views.unfollow,name='unfollow'),
    
]

my_social_project/app_post/urls.py
from app_post import views
from django.urls import path


app_name='app_post'


urlpatterns=[
    path('',views.home,name='home')
]

my_social_project/my_social_project/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.contrib.staticfiles.urls import static,staticfiles_urlpatterns
from app_post import views
urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/',include('app_login.urls')),
    path('post/',include('app_post.urls')),
    path('',views.home,name='home'),
]

urlpatterns+=static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)
urlpatterns+=static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)

my_social_project/app_post/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class Posts(models.Model):
    author=models.ForeignKey(User,on_delete=models.CASCADE,related_name='post')
    image=models.ImageField(upload_to='post_images')
    caption=models.CharField(max_length=264,blank=True)
    upload_date=models.DateTimeField(auto_now_add=True)
    update_date=models.DateTimeField(auto_now=True)
    
    class Meta:
        ordering=['-upload_date']


class Like(models.Model):
    post=models.ForeignKey(Posts,on_delete=models.CASCADE,related_name='liked_post')
    user=models.ForeignKey(User,on_delete=models.CASCADE,related_name='liker')
    date_created=models.DateTimeField(auto_now_add=True)
    
    def __str__(self):
        return '{}:{}'.format(self.user, self.post)
    

my_social_project/app_post/forms.py
from django import forms


from app_post.models import Posts

class PostForm(forms.ModelForm):
    class Meta:
        model = Posts
        fields=['image','caption']
        

my_social_project/app_post/views.py
from django.shortcuts import render
from django.shortcuts import HttpResponse,HttpResponseRedirect
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from app_login.models import UserProfile,Follow
from app_post.models import Posts,Like
from django.urls import reverse_lazy,reverse

# Create your views here.
@login_required
def home(request):
    following_list=Follow.objects.filter(follower=request.user)
    posts=Posts.objects.filter(author__in=following_list.values_list("following"))
    if request.method=="GET":
        search=request.GET.get('search','')
        result=User.objects.filter(username__icontains=search)
    return render (request,'app_post/home.html',context={'title':'Home', "search":search,'result':result,'following_list':following_list,'posts':posts})

@login_required
def liked(request,pk):
    post=Posts.objects.get(pk=pk)
    already_liked=Like.objects.filter(post=post,user=request.user)
    if not already_liked:
        liked_post=Like(post=post,user=request.user)
        liked_post.save()
    return HttpResponseRedirect(reverse('home'))


@login_required
def unliked(request,pk):
    post=Posts.objects.get(pk=pk)
    already_liked=Like.objects.filter(post=post,user=request.user)   
    already_liked.delete()
    return HttpResponseRedirect(reverse('home'))     
    

my_social_project/templates/app_post/home.html
{% extends 'navbar.html' %}
{% block title_block %}
    {{ title }}
{% endblock %}

{% block content %}
    {% if search %}
        {% for user in result %}
            <div class="row mb-3">
                <div class="col-sm-2">
                    {% if user.user_profile.profile_pic %}
                        <img src="/media/{{ user.user_profile.profile_pic }}" width="50px" height="50px" class="rounded-circle" alt="">
                    {% else %}
                        <img src="/media/profile_pics/profile-pic.jpg" width="50px" height="50px" class="rounded-circle" alt="">
                    {% endif %}
                </div>
                <div class="col-sm-10">
                    <a href="{% url 'app_login:user' username=user.username %}">{{ user.username }}</a>
                    <br>
                    {{ user.user_profile.full_name }}
                </div>
            </div>
        {% endfor %}
    {% else %}
        <div class="row">
            <div class="col-sm-9">
                {% for post in posts %}
                    <div style="border:1px solid #888888">
                        <div class="post-header p-3 d-flex align-items-center">
                            {% if post.author.user_profile.profile_pic %}
                                <img src="/media/{{ user.user_profile.profile_pic }}" width="40px" height="40px" class="rounded-circle" alt="">
                            {% else %}
                                <img src="/media/profile_pics/profile-pic.jpg" width="40px" height="40px" class="rounded-circle" alt="">
                            {% endif %}
                            <a href="{% url 'app_login:user' username=post.author %}" class="ms-2">{{ post.author}}</a>
                        </div>
                        <img src="/media/{{post.image}}" width="100%"></img>
                        <div style="padding:20px">
                            <i class="fa-solid fa-thumbs-up"></i>
                            <i class="fa-solid fa-thumbs-down"></i>
                        </div>
                        
                    </div>
                    <br>
                    <br>
                {% endfor %}
            </div>
            <div class="col-sm-3">
                <div class="profile-summary">
                    <div class="row mb-3">
                        <div class="col-sm-4">
                            {% if user.user_profile.profile_pic %}
                                <img src="/media/{{ user.user_profile.profile_pic }}" width="40px" height="40px" class="rounded-circle" alt="">
                            {% else %}
                                <img src="/media/profile_pics/profile-pic.jpg" width="40px" height="40px" class="rounded-circle" alt="">
                            {% endif %}
                        </div>
                        <div class="col-sm-8">
                            {{ user.username }}
                            <br>
                            {{ user.user_profile.full_name }}
                        </div>
                    </div>
                </div>
            </div>
        </div>
    {% endif %}
{% endblock %}